### ISSUE TITLE
Need to find wich field changed or data inserted

### ISSUE THREAD

**Issue by mjanbazi** [xiidea/EasyAuditBundle#9]
hello
i want to find when i updated entity,which fields changed with changed value , like this
Table1 and Field1 This Value V1 Changed to V2
(parameter: Table1,Field1,V1,V2)

and when i inserted a data in table this log:
Table1 and Field1 This Value V1 Inserted,Field2 This Value V2 Insertet
(parameter: Table1,Field1,Field2,V1,V2)

for each field in table all of them in one string stored in a row in audit_log table

thank you

**Comment by ronisaha** [comment]
You can add as many row as you need in your audit entity. And use pre-persist listener to filled the data like [this](https://github.com/xiidea/EasyAuditBundle/blob/master/Resources/doc/pre-persist-listener.md)

**Comment by braianj** [comment]
Hi @ronisaha do you have an example for saving old_data / new_data as json or something similar?

**Comment by ronisaha** [comment]
You can check sample implementation to store the changed data. You can create your own entity event resolver following that sample.

**Comment by braianj** [comment]
@ronisaha with the example it throw

> The file "/project/app/config/services.yml" does not contain valid YAML in /project/app/config/services.yml (which is being imported from "/project/app/config/config.yml").
with 

```
    audit_trail.entity_event_resolver:
        class: AppBundle\Resolver\EntityEventResolver
        calls:
            - [ setContainer,[ @service_container ] ]
```
